language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install pipenv
  - pipenv install

activate:
  - pipenv shell -c

before_script:
  - psql -U postgres -c "CREATE DATABASE geodjango;"
  - psql -U postgres -c "CREATE USER geodjango WITH PASSWORD 'geodjango';"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE geodjango TO geodjango;"
  - psql -U geodjango -d geodjango -c "CREATE EXTENSION postgis;"